name: github-action

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['8.6.5', '8.8.4', 8.10.2]
        os: ['ubuntu-latest', 'macos-latest']
    name: Haskell GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Haskell
        uses: actions/setup-haskell@v1.1
        with:
          ghc-version: ${{ matrix.ghc }}
          cabal-version: ${{ matrix.cabal }}
      - name: Cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
        uses: actions/cache@v2
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}
      - name: install postgres (linux)
        run: |
          sudo apt-get update
          sudo apt-get install postgresql-10
          export PATH=$PATH:/usr/lib/postgresql/10/bin
          which pg_ctl
          echo "/usr/lib/postgresql/10/bin" >> $GITHUB_PATH
        if: matrix.os == 'ubuntu-latest'
      - name: install postgres (macos)
        run: |
          brew update
          brew install postgresql@10
          export PATH=$PATH:`brew --prefix`/bin
          which pg_ctl
          echo "$(brew --prefix)/bin" >> $GITHUB_PATH
        if: matrix.os == 'macos-latest'
      - name: build all
        run: cabal build all
