language: nix
nix: 2.2.2

jobs:
  include:
    - stage: Build
      env: OS=linux GHCVER=ghc865
    - stage: Build
      env: OS=linux GHCVER=ghc881
    - env: OS=macos GHCVER=ghc865
      os: osx
      # Fix OSX, see https://travis-ci.community/t/cannot-use-nix-support-on-osx/2927
      language: generic
      before_install:
      - curl https://nixos.org/nix/install | sh
      - source /Users/travis/.nix-profile/etc/profile.d/nix.sh
    - env: OS=macos GHCVER=ghc881
      os: osx
      # Fix OSX, see https://travis-ci.community/t/cannot-use-nix-support-on-osx/2927
      language: generic
      before_install:
      - curl https://nixos.org/nix/install | sh
      - source /Users/travis/.nix-profile/etc/profile.d/nix.sh

install:
- sudo mkdir -p /etc/nix
- echo "substituters = https://cache.nixos.org https://hydra.iohk.io" | sudo tee -a /etc/nix/nix.conf > /dev/null
- echo "trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ=" | sudo tee -a /etc/nix/nix.conf > /dev/null

script:
- nix-build --argstr haskellCompiler $GHCVER -A hsPkgs.jsaddle.components.library
- nix-build --argstr haskellCompiler $GHCVER -A hsPkgs.jsaddle-warp.components.library
- nix-build --argstr haskellCompiler $GHCVER -A hsPkgs.jsaddle-clib.components.library
- |
  if [ "$OS" == "macos" ]; then
    nix-build --argstr haskellCompiler $GHCVER -A hsPkgs.jsaddle-wkwebview.components.library
  fi
# TODO try to find how to get working webkitgtk with nix on macOS
- |
  if [ "$OS" != "macos" ]; then
    nix-build --argstr haskellCompiler $GHCVER -A hsPkgs.jsaddle-webkit2gtk.components.library
  fi

notifications:
  irc:
    channels: "irc.freenode.net#ghcjs"
  email: true
